use_frameworks!

platform :ios, '9.0'

target 'LDZFVoiceConvert_Example' do
#  pod 'LDZFVoiceConvert', :path => '../'
  pod 'LDZFVoiceConvert'

  target 'LDZFVoiceConvert_Tests' do
    inherit! :search_paths

    
  end
end
